### HelloWorld - JSON
POST http://localhost:8080/HelloWorld/
Content-Type: application/json

{
    "InputDetails": {
        "Name": "Rahul"
    }
}

### HelloWorld - Detailed Execution
POST http://localhost:8080/HelloWorld/dmnresult
Content-Type: application/json

{
    "InputDetails": {
        "Name": "Rahul"
    }
}

### DMN Definition
GET http://localhost:8080/HelloWorld