### HelloWorld
POST http://localhost:8080/HelloWorld/
Content-Type: application/json

{
    "InputDetails": {
        "Name": "Rahul"
    }
}

### HelloWorld - Detailed Execution
POST http://localhost:8080/HelloWorld/dmnresult
Content-Type: application/json

{
    "InputDetails": {
        "Name": "Rahul"
    }
}

### DMN Definition
GET http://localhost:8080/HelloWorld


### Fibonacci 
POST http://localhost:8080/Fibonacci/
Content-Type: application/json

{"NElement":9}


### Location
POST http://localhost:8080/Location/
Content-Type: application/json

{"ZipCode":5500}

### DateOperations
POST http://localhost:8080/DateOperations/
Content-Type: application/json

{
    "FromDate": "2022-06-01",
    "ToDate": "2022-06-09",
    "Cycle": "A",
    "Tenure": 2
}