### https://documentation.signavio.com/suite/en-us/Content/process-manager/userguide/dmn-literal-expressions.htm#day
### https://docs.camunda.io/docs/components/modeler/feel/what-is-feel/

### HelloWorld
POST http://localhost:8080/HelloWorld/
Content-Type: application/json

{
    "InputDetails": {
        "Name": "Rahul"
    }
}

### HelloWorld - Detailed Execution
POST http://localhost:8080/HelloWorld/dmnresult
Content-Type: application/json

{
    "InputDetails": {
        "Name": "Rahul"
    }
}

### DMN Definition
GET http://localhost:8080/HelloWorld


### Fibonacci 
POST http://localhost:8080/Fibonacci/
Content-Type: application/json

{"NElement":9}


### Location
POST http://localhost:8080/Location/
Content-Type: application/json

{"ZipCode":5500}

### DateOperations
POST http://localhost:8080/DateOperations/
Content-Type: application/json

{
    "FromDate": "2022-06-01",
    "ToDate": "2022-06-09",
    "Cycle": "A",
    "Tenure": 2
}

### Polynomial
POST http://localhost:8080/Polynomial/
Content-Type: application/json

{
    "Data": "lul"
}

### TrafficViolation
POST http://localhost:8080/TrafficViolation/
Content-Type: application/json

{
	"Driver": {
		"Name": "John Doe",
		"Age": 19,
		"State": "California",
		"City": "Los Angeles",
		"Points": 14
	},
	"Violation": {

		"Code": "001",
		"Date": "2020-11-03",
		"Type": "Speed",
		"SpeedLimit": 100,
		"ActualSpeed": 200
	}
}

### TrafficViolation
POST http://localhost:8080/TrafficViolation/DriverSuspention
Content-Type: application/json

{
	"Driver": {
		"Name": "John Doe",
		"Age": 19,
		"State": "California",
		"City": "Los Angeles",
		"Points": 17
	},
	"Violation": {
		"Code": "001",
		"Date": "2020-11-03",
		"Type": "Speed",
		"SpeedLimit": 100,
		"ActualSpeed": 200
	}
}

### Yearfraction
### https://stackoverflow.com/questions/43355292/replicating-yearfrac-function-from-excel-in-python
### https://lists.oasis-open.org/archives/office-formula/200806/msg00039.html
### https://kalotay.com/SupportingDocumentation/BondOAS/daycounts.html
### https://www.iotafinance.com/en/Date-Calculator.html
### https://support.microsoft.com/en-us/office/yearfrac-function-3844141e-c76d-4143-82b6-208454ddc6a8#:~:text=Description,assign%20to%20a%20specific%20term.
### https://stackoverflow.com/questions/43355292/replicating-yearfrac-function-from-excel-in-python

### 30US/360 - 3.08611
POST http://localhost:8080/YearFact/
Content-Type: application/json

{
	"Basis": "30US/360",
    "StartDt": "2022-02-28",
    "EndDt": "2025-03-31"
}
### 30EU/360 - 3.08888
POST http://localhost:8080/YearFact/
Content-Type: application/json

{
	"Basis": "30EU/360",
    "StartDt": "2022-02-28",
    "EndDt": "2025-03-31"
}
### 365/365 - 3.087671
POST http://localhost:8080/YearFact/
Content-Type: application/json

{
	"Basis": "365/365",
    "StartDt": "2022-02-28",
    "EndDt": "2025-03-31"
}
### Actual/Actual - 3.085557
POST http://localhost:8080/YearFact/
Content-Type: application/json

{
	"Basis": "Actual/Actual",
    "StartDt": "2022-02-28",
    "EndDt": "2025-03-31"
}
### Actual/360 - 3.130555
POST http://localhost:8080/YearFact/
Content-Type: application/json

{
	"Basis": "Actual/360",
    "StartDt": "2022-02-28",
    "EndDt": "2025-03-31"
}
### Actual/365 - 3.087671
POST http://localhost:8080/YearFact/
Content-Type: application/json

{
	"Basis": "Actual/365",
    "StartDt": "2022-02-28",
    "EndDt": "2025-03-31"
}
### 365/365 - 3.084931
POST http://localhost:8080/YearFact/
Content-Type: application/json

{
	"Basis": "365/365",
    "StartDt": "2022-02-28",
    "EndDt": "2025-03-31"
}

### LoanCalculator-EPI
POST http://localhost:8080/LoanCalculator/
Content-Type: application/json

{
    "LoanDetails": {
        "AmtFinanced": 12000,
        "Term": 20,
        "Rate": 10,
        "ContractDt": "2020-01-21",
        "FirstPmtDt": "2020-03-01"
    },
    "ProductDetails": {
        "BillingCycle": "Monthly",
        "Basis": "30US/360",
        "InstallmentType":"EIP"
    }
}

### LoanCalculator-EIP
POST http://localhost:8080/LoanCalculator/
Content-Type: application/json

{
    "LoanDetails": {
        "AmtFinanced": 12000,
        "Term": 20,
        "Rate": 10,
        "ContractDt": "2020-01-21",
        "FirstPmtDt": "2020-03-01"
    },
    "ProductDetails": {
        "BillingCycle": "Monthly",
        "Basis": "30US/360",
        "InstallmentType":"EIP"
    }
}